### ISSUE TITLE
DaiFaucet contract mistake

### ISSUE THREAD

**Issue by KadenZipfel** [makerdao/developerguides#22]
In the `DaiFaucet` contract,  it checks to see if the `withdraw_amount` parameter is <= 0.1 ether, when it should just be 0.1.

So instead of:
`require(withdraw_amount <= 0.1 ether);`

It should be:

`require(withdraw_amount <= 0.1);`

Edit: It's not that simple to work with decimals in Solidity, so I'm not entirely sure what the solution would be. We can still limit it in Ether, but it would have to be much less than 0.1 eth. I will be using 0.0005 eth for mine.

**Comment by KadenZipfel** [comment]
This can also be seen in the remix screenshot right below the contract, so that should probably be fixed as well.

**Comment by pcatana** [comment]
The example was written with this in mind: https://solidity.readthedocs.io/en/v0.4.24/units-and-global-variables.html#ether-units
