### ISSUE TITLE
Invalid link to DAI documentation

### ISSUE THREAD

**Issue by adamskrodzki** [makerdao/developerguides#28]
On Page

https://github.com/makerdao/developerguides/blob/master/cdp/cdp-integration-guide/cdp-integration-guide.md

in Daj.js section
there is a link

https://makerdao.com/documentation/

which leads to nowhere

Title link of a section also leads to nowhere

**Comment by pcatana** [comment]
Link has been updated: https://github.com/makerdao/developerguides/blob/master/vault/vault-integration-guide/cdp-integration-guide.md#daijs

We'll add new link once we get the new documentation covering MCD
