### ISSUE TITLE
SAI upgrade: Terms of service not available via link

### ISSUE THREAD

**Issue by bh2smith** [makerdao/developerguides#31]
On the SAI to DAI upgrade page, there is a link to "Terms of Service"

![Screenshot 2019-11-18 at 21 48 04](https://user-images.githubusercontent.com/11778116/69092659-2a7fce80-0a4d-11ea-933c-f73d57b18180.png)

which redirects to [https://migrate.makerdao.com/terms](https://migrate.makerdao.com/terms) which is the following page:

![Screenshot 2019-11-18 at 21 49 46](https://user-images.githubusercontent.com/11778116/69092765-67e45c00-0a4d-11ea-92cf-a72688b0cdb0.png)

I would like to be able to access these terms before such an upgrade.

**Comment by pcatana** [comment]
It's been updated: https://migrate.makerdao.com/terms/
