### ISSUE TITLE
A problem occurred while interacting with contracts using seth

### ISSUE THREAD

**Issue by ritik99** [makerdao/developerguides#73]
Hey,

I tried to deploy the Maker testchain using the instructions provided here: [https://github.com/makerdao/developerguides/blob/master/devtools/test-chain-guide/test-chain-guide.md](https://github.com/makerdao/developerguides/blob/master/devtools/test-chain-guide/test-chain-guide.md). While trying to run the command: `seth send -F $ETH_FROM $CDP_MANAGER 'open(bytes32,address)' "$ilk" "$ETH_FROM"`, I receive the following error: `curl: (52) Empty reply from server`. If I run the testchain with `--verbose` the following error is returned when I run the previous seth command: 

    eth_sendTransaction
    Error: Callback was already called.
        at /Users/ritikdutta/Desktop/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:62:273
        at s.<anonymous> (/Users/ritikdutta/Desktop/testchain/node_modules/ganache-cli/build/ganache- 
    core.node.cli.js:62:2116)
        at s.emit (events.js:314:20)
        at s.destroy (/Users/ritikdutta/Desktop/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:32:17222)
        at finish (_stream_writable.js:670:14)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by pcatana** [comment]
Hey!
So, you fixed the issue?

**Comment by ritik99** [comment]
Hey,

Sorry, yes, the error didn't show up when I ran `scripts/launch` instead of `scripts/launch -s default --fast`. In subsequent runs `scripts/launch -s default --fast` worked just fine as well. Was a little too quick in opening the issue haha.
