### ISSUE TITLE
Error: requests.exceptions.ConnectionError: HTTPSConnectionPool 

### ISSUE THREAD

**Issue by optima66** [makerdao/developerguides#75]
Hello 
I followed your tutorial and got an error:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //93ad48d9e784fd857d160044772e35.eth.rpc.rivet.cloud/:8545 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7b9ef7cfd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

This is my .sh file:

```

#!/bin/bash
/home/user/simple-arbitrage-keeper/bin/simple-arbitrage-keeper \
 --rpc-host 'https://93ad48d884d857d160044772e35.eth.rpc.rivet.cloud/' \
 --eth-from '0xD63e5265f0033FA77a316516f768d26F7f879F6a' \
 --eth-key 'key_file=/home/user/.ethereum/keystore/UTC--2020-10-06T15-07-58.672992832Z--d63e5265ffa77a316516f768d26f7f879f6a' \
 --uniswap-entry-exchange '0x47D4Af3BBaEC0dE4dba5F44ae8Ed2761977D32d6' \
 --uniswap-arb-exchange '0x1D79BcC198281C5F9B52bf24F671437BaDd3a688' \
 --oasis-address '0x4A6bC4e803c62081ffEbCc8d227B5a87a58f1F8F' \
 --oasis-api-endpoint 'https://kovan-api.oasisdex.com' \
 --entry-token '0xC4375B7De8af5a38a93548eb8453a498222C4fF2' \
 --arb-token '0xd0A1E359811322d97991E03f863a0C30C2cF029C' \
 --arb-token-name 'WETH' \
 --min-profit 1 \
 --max-engagement 10 \

```

what do I do?

**Comment by Joe-mcgee** [comment]
Not sure, but what sticks out to me is that forward slash ending on your --rpc-host.  I wouldn't be bothered by it normally but your error returns ```...rivet.cloud/:8545``` looks like the back end is trying to concat the port, not inject the port on the domain.  What happens if you change ``` --rpc-host 'https://93ad48d884d857d160044772e35.eth.rpc.rivet.cloud/' \``` to ``` --rpc-host 'https://93ad48d884d857d160044772e35.eth.rpc.rivet.cloud' \```?

**Comment by Lukasz257** [comment]
Yes
